package io.effectivelabs.durable.adapter.postgres

import io.effectivelabs.durable.domain.port.IdGenerator

/**
 * No-op ID generator for the Postgres adapter.
 * The ready_queue.id column is auto-generated by the DB (BIGSERIAL),
 * so this value is never inserted and can safely be zero.
 */
class NoOpIdGenerator : IdGenerator {
    override fun nextQueueId(): Long = 0L
}
